rawdata = $(wildcard data/*/*.csv)
processed-data/iris/iris-train1.csv processed-data/iris/iris-train2.csv processed-data/iris/iris-train3.csv processed-data/iris/iris-train4.csv processed-data/iris/iris-test1.csv processed-data/iris/iris-test2.csv processed-data/iris/iris-test3.csv processed-data/iris/iris-test4.csv processed-data/iris/iris-trainy.csv processed-data/iris/iris-testy.csv : data/iris/Iris.csv code/preprocessing.R
	Rscript code/preprocessing.R data/iris/Iris.csv iris Species

processed-data/glass/glass-train1.csv processed-data/glass/glass-train2.csv processed-data/glass/glass-train3.csv processed-data/glass/glass-train4.csv processed-data/glass/glass-test1.csv processed-data/glass/glass-test2.csv processed-data/glass/glass-test3.csv processed-data/glass/glass-test4.csv processed-data/glass/glass-trainy.csv processed-data/glass/glass-testy.csv : data/glass/glass.csv code/preprocessing.R
	Rscript code/preprocessing.R data/glass/glass.csv glass Type

processed-data/no-show/no-show-train1.csv processed-data/no-show/no-show-train2.csv processed-data/no-show/no-show-train3.csv processed-data/no-show/no-show-train4.csv processed-data/no-show/no-show-test1.csv processed-data/no-show/no-show-test2.csv processed-data/no-show/no-show-test3.csv processed-data/no-show/no-show-test4.csv processed-data/no-show/no-show-trainy.csv processed-data/no-show/no-show-testy.csv : data/no-show/No-show-Issue-Comma-300k.csv code/preprocessing.R
	Rscript code/preprocessing.R data/no-show/No-show-Issue-Comma-300k.csv no-show Status

processed-data/speeddate/speeddate-train1.csv processed-data/speeddate/speeddate-train2.csv processed-data/speeddate/speeddate-train3.csv processed-data/speeddate/speeddate-train4.csv processed-data/speeddate/speeddate-test1.csv processed-data/speeddate/speeddate-test2.csv processed-data/speeddate/speeddate-test3.csv processed-data/speeddate/speeddate-test4.csv processed-data/speeddate/speeddate-trainy.csv processed-data/speeddate/speeddate-testy.csv : data/speed-date/speed-date.csv code/preprocessing.R
	Rscript code/preprocessing.R data/speed-date/speed-date.csv speeddate match

processed-data/housing/housing-train1.csv processed-data/housing/housing-train2.csv processed-data/housing/housing-train3.csv processed-data/housing/housing-train4.csv processed-data/housing/housing-test1.csv processed-data/housing/housing-test2.csv processed-data/housing/housing-test3.csv processed-data/housing/housing-test4.csv processed-data/housing/housing-trainy.csv processed-data/housing/housing-testy.csv : data/kc_house/kc_house_data.csv code/preprocessing.R
	Rscript code/preprocessing.R data/kc_house/kc_house_data.csv housing price

processed-data/housing/housing-train1.csv processed-data/housing/housing-train2.csv processed-data/housing/housing-train3.csv processed-data/housing/housing-train4.csv processed-data/housing/housing-test1.csv processed-data/housing/housing-test2.csv processed-data/housing/housing-test3.csv processed-data/housing/housing-test4.csv processed-data/housing/housing-trainy.csv processed-data/housing/housing-testy.csv : data/kc_house/kc_house_data.csv code/preprocessing.R
	Rscript code/preprocessing.R data/kc_house/kc_house_data.csv housing price

.PHONY : preprocess

preprocess : processed-data/iris/iris-train1.csv processed-data/iris/iris-train2.csv processed-data/iris/iris-train3.csv processed-data/iris/iris-train4.csv processed-data/iris/iris-test1.csv processed-data/iris/iris-test2.csv processed-data/iris/iris-test3.csv processed-data/iris/iris-test4.csv processed-data/iris/iris-trainy.csv processed-data/iris/iris-testy.csv processed-data/glass/glass-train1.csv processed-data/glass/glass-train2.csv processed-data/glass/glass-train3.csv processed-data/glass/glass-train4.csv processed-data/glass/glass-test1.csv processed-data/glass/glass-test2.csv processed-data/glass/glass-test3.csv processed-data/glass/glass-test4.csv processed-data/glass/glass-trainy.csv processed-data/glass/glass-testy.csv processed-data/no-show/no-show-train1.csv processed-data/no-show/no-show-train2.csv processed-data/no-show/no-show-train3.csv processed-data/no-show/no-show-train4.csv processed-data/no-show/no-show-test1.csv processed-data/no-show/no-show-test2.csv processed-data/no-show/no-show-test3.csv processed-data/no-show/no-show-test4.csv processed-data/no-show/no-show-trainy.csv processed-data/no-show/no-show-testy.csv processed-data/speeddate/speeddate-train1.csv processed-data/speeddate/speeddate-train2.csv processed-data/speeddate/speeddate-train3.csv processed-data/speeddate/speeddate-train4.csv processed-data/speeddate/speeddate-test1.csv processed-data/speeddate/speeddate-test2.csv processed-data/speeddate/speeddate-test3.csv processed-data/speeddate/speeddate-test4.csv processed-data/speeddate/speeddate-trainy.csv processed-data/speeddate/speeddate-testy.csv processed-data/housing/housing-train1.csv processed-data/housing/housing-train2.csv processed-data/housing/housing-train3.csv processed-data/housing/housing-train4.csv processed-data/housing/housing-test1.csv processed-data/housing/housing-test2.csv processed-data/housing/housing-test3.csv processed-data/housing/housing-test4.csv processed-data/housing/housing-trainy.csv processed-data/housing/housing-testy.csv
